POST http://localhost:5000/auth/register HTTP/1.1
content-type: application/json

{
    "Name": "testy",
    "Surname": "pwi",
    "Email": "testypwi@gmail.com",
    "Street": "kozia",
    "PostalCode": "08-800",
    "City": "Warszawa",
    "CountryId": 5,
    "Phone": "500 300 300",
    "Password": "haslo"
}

############################################
GET http://localhost:5000/auth HTTP/1.1

#############################################

POST http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "Email": "testypwi@gmail.com",
    "Password": "haslo2
    "
}

##########################################3
GET http://localhost:5000/country HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3IiwidW5pcXVlX25hbWUiOiJ0ZXN0QGdtYWlsLmNvbSIsIm5iZiI6MTU5MDQyMDUzMiwiZXhwIjoxNTkwNTA2OTMyLCJpYXQiOjE1OTA0MjA1MzJ9.LTPsAs3JVlX-kioDroqHZDcgEyPH-mS2A31rYy8SY7QwUthBzgh5SXOoEcXGWGV-Iev4uCWQEbnOwhrSk0rvRA
 

#######################################################################################

PUT http://localhost:5000/user HTTP/1.1
content-type: application/json

{
    "Id": 8,
    "Name": "Wojtesadasdk",
    "Surname": "Wojtkowski",
    "Email": "dada@gmail.com",
    "Street": "kozia",
    "PostalCode": "08-800",
    "City": "Warszawa",
    "CountryId": 5,
    "Phone": "500 300 303"
}

############################################

GET http://localhost:5000/user/resetPassword?email=testypwi@gmail.com HTTP/1.1

#############################################

POST http://localhost:5000/user/changePassword HTTP/1.1
content-type: application/json

{
    "Email": "testypwi@gmail.com",
    "Token": "6a5dab30-7343-4b3f-9c88-97fbef04c591",
    "NewPassword": "haslo2"
}

##############################################

GET http://localhost:5000/stations HTTP/1.1
